//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tweeter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Person
    {
        public Person()
        {
            this.followings = new HashSet<following>();
            this.tweets = new HashSet<tweet>();
        }
        [Display(Name = "Username")]
        [Required(ErrorMessage = "Please enter user name")]
        [MaxLength(length: 25, ErrorMessage = "Maximum length 25 exceeded")]

        public string user_id { get; set; }
        [Display(Name = "Password")]
        [Required(ErrorMessage = "Please enter password")]
        [MaxLength(length: 100, ErrorMessage = "Maximum length 100 exceeded")]

        public string password { get; set; }
        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Please enter full name")]
        [MaxLength(length: 30, ErrorMessage = "Maximum length 30 exceeded")]

        public string fullName { get; set; }
        [Display(Name = "Email")]
        [Required(ErrorMessage = "Please enter email id")]
        [MaxLength(length: 50, ErrorMessage = "Maximum length 50 exceeded")]
        [EmailAddress]

        public string email { get; set; }
        public System.DateTime Joined { get; set; }
        public bool active { get; set; }

        public virtual ICollection<following> followings { get; set; }
        public virtual ICollection<tweet> tweets { get; set; }
    }
}
