//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeModelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesLeaveTracking
    {
        public int RowId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime LeaveFromDate { get; set; }
        public System.DateTime LeaveToDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Comments { get; set; }
        public Nullable<int> SupervisorId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
