//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeModelMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.EmployeesLeaveTrackings = new HashSet<EmployeesLeaveTracking>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string WorkingArea { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual EmployeeLeaveDeail EmployeeLeaveDeail { get; set; }
        public virtual EmployeeLeaveDeail EmployeeLeaveDeail1 { get; set; }
        public virtual ICollection<EmployeesLeaveTracking> EmployeesLeaveTrackings { get; set; }
    }
}
